### ISSUE TITLE
lparallel-test not in Quicklisp repository

### ISSUE THREAD

**Issue by senor-hadoop** [lmj/lparallel#24]
The documentation:

https://lparallel.org/download/

says:

"To run the test suite,

(ql:quickload :lparallel-test)
(lparallel-test:execute)"

However this produces an error at the ql:quickload step, saying the system is not found. Indeed, checking at https://www.quicklisp.org/beta/releases.html, one can see that lparallel-test is not included in quicklisp.

**Comment by lmj** [comment]
The system was recently excluded from the Quicklisp database due to a warning in lparallel-test when compiling with a recent SBCL. I've committed a fix which should be propagated to the next Quicklisp release.

Note  `(ql:quickload :lparallel-test)` has always worked when lparallel is installed locally, since `quickload` muffles warnings by default.

Thanks.
